//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReederPDI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PDIEntities : DbContext
    {
        public PDIEntities()
            : base("name=PDIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TableBoxProblem> TableBoxProblem { get; set; }
        public virtual DbSet<TableCameraProblem> TableCameraProblem { get; set; }
        public virtual DbSet<TableChargeProblem> TableChargeProblem { get; set; }
        public virtual DbSet<TableDevices> TableDevices { get; set; }
        public virtual DbSet<TableFlexProblem> TableFlexProblem { get; set; }
        public virtual DbSet<TableLCDProblem> TableLCDProblem { get; set; }
        public virtual DbSet<TableLogin> TableLogin { get; set; }
        public virtual DbSet<TableMotherBoardProblem> TableMotherBoardProblem { get; set; }
        public virtual DbSet<TableNetworkProblem> TableNetworkProblem { get; set; }
        public virtual DbSet<TablePDI> TablePDI { get; set; }
        public virtual DbSet<TableSoundProblem> TableSoundProblem { get; set; }
        public virtual DbSet<TableTocuhProblem> TableTocuhProblem { get; set; }
        public virtual DbSet<TablePDI_UPDATED> TablePDI_UPDATED { get; set; }
    }
}
