//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReederPDI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableSoundProblem
    {
        public int ID_Sound { get; set; }
        public string VP000_Sound { get; set; }
    }
}
