//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReederPDI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableCameraProblem
    {
        public int ID_Camera { get; set; }
        public string CP000_Camera { get; set; }
    }
}
