//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReederPDI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TablePDI_UPDATED
    {
        public int ID { get; set; }
        public string SERIALNO { get; set; }
        public string Date { get; set; }
        public string IMEINO1 { get; set; }
        public string IMEINO2 { get; set; }
        public string Device { get; set; }
        public string TP000 { get; set; }
        public string LP000 { get; set; }
        public string PP000 { get; set; }
        public string BP000 { get; set; }
        public string CP000 { get; set; }
        public string NP000 { get; set; }
        public string VP000 { get; set; }
        public string SP000 { get; set; }
        public string JP000 { get; set; }
    }
}
