//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReederPDI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class TablePDI
    {
        public int ID { get; set; } //THIS
        public string SERIALNO { get; set; }
        public string Date { get; set; }
        public string IMEINO1 { get; set; }
        public string IMEINO2 { get; set; }

        //TOUCH PROBLEM

        public string TP000 { get; set; } //THIS

        [NotMapped] //THISN

        public IEnumerable<TableTocuhProblem> GetTP000List { get; set; } //THISN

        [NotMapped] //THISN

        public string[] SelectedIDArray { get; set; } //THISN

        //LCD PROBLEM

        public string LP000 { get; set; }

        [NotMapped] //THISN

        public IEnumerable<TableLCDProblem> GetLP000List { get; set; } //THISN

        [NotMapped] //THISN

        public string[] SelectedID1Array { get; set; } //THISN

        //MOTHERBOARD PROBLEM

        public string PP000 { get; set; } //THIS

        [NotMapped] //THISN

        public IEnumerable<TableMotherBoardProblem> GetPP000List { get; set; } //THISN

        [NotMapped] //THISN

        public string[] SelectedID2Array { get; set; } //THISN

        //CHARGE PROBLEM

        public string BP000 { get; set; } //THIS

        [NotMapped] //THISN

        public IEnumerable<TableChargeProblem> GetBP000List { get; set; } //THISN

        [NotMapped] //THISN

        public string[] SelectedID3Array { get; set; } //THISN

        //CAMERA PROBLEM

        public string CP000 { get; set; } //THIS

        [NotMapped] //THISN

        public IEnumerable<TableCameraProblem> GetCP000List { get; set; } //THISN

        [NotMapped] //THISN

        public string[] SelectedID4Array { get; set; } //THISN

        //NETWORK PROBLEM

        public string NP000 { get; set; } //THIS

        [NotMapped] //THISN

        public IEnumerable<TableNetworkProblem> GetNP000List { get; set; } //THISN

        [NotMapped] //THISN

        public string[] SelectedID5Array { get; set; } //THISN

        //SOUND PROBLEM

        public string VP000 { get; set; } //THIS

        [NotMapped] //THISN

        public IEnumerable<TableSoundProblem> GetVP000List { get; set; } //THISN

        [NotMapped] //THISN

        public string[] SelectedID6Array { get; set; } //THISN

        //FLEX PROBLEM

        public string SP000 { get; set; } //THIS

        [NotMapped] //THISN

        public IEnumerable<TableFlexProblem> GetSP000List { get; set; } //THISN

        [NotMapped] //THISN

        public string[] SelectedID7Array { get; set; } //THISN

        //BOX PROBLEM

        public string JP000 { get; set; } //THIS

        [NotMapped] //THISN

        public IEnumerable<TableBoxProblem> GetJP000List { get; set; } //THISN

        [NotMapped] //THISN

        public string[] SelectedID8Array { get; set; } //THISN

        //DEVÝCE

        public string Device { get; set; }

        [NotMapped] //THISN

        public IEnumerable<TableDevices> GetDeviceList { get; set; } //THISN

        [NotMapped] //THISN

        public string[] SelectedID9Array { get; set; } //THISN
    }
}
